export {default as About} from './about/About'
export {default as Book} from './book/Book'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as Location} from './location/Location'
export {default as Services} from './services/Services'
export {default as Gallery} from './gallery/Gallery'